const ERROR_CODE = {
  NOT_FOUND: 'NOT_FOUND',
  MISSING: 'MISSING',
  ID_MALFORMED: 'ID_MALFORMED',
  IS_EMPTY: 'IS_EMPTY',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  MUST_BE_BOOLEAN: 'Must be a boolean true or false',
  MUST_BE_NUMBER: 'INALID NUMBER',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT_MIN_5',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
}

export { ERROR_CODE }
